### ISSUE TITLE
Contentful::Array does not implement #to_ary

### ISSUE THREAD

**Issue by arielkirkwood** [contentful/contentful.rb#200]
Hi folks, thanks for your hard work on this gem and the other Ruby client libraries!

I'm working with a Rails 4.2.11.1 project and the latest version of `contentful_rails` (0.4.2), which bundles `contentful_model` (1.0.1) and `contentful` (2.12.0). When I retrieve a collection of entries, I get a `Contentful::Array` object returned; within Rails, I'd like to be able to pass this object to the `render` method in my view to render a view template for each element of the array. To this end, my Contentful model has `extend ActiveModel::Naming` and `include ActiveModel::Conversion` implemented so that Rails knows how to find an associated view template for a given Contentful model; where I'm getting stuck is the initial `render` call with the `Contentful::Array` as an argument. Rails tries to figure out if the argument is a single object or a collection, using `respond_to?(:to_ary)` as a test ([source](https://github.com/rails/rails/blob/v4.2.11.1/actionview/lib/action_view/renderer/partial_renderer.rb#L409)).

Since `Contentful::Array` does not implement `to_ary`, Rails thinks it is a singular object, but since `Contentful::Array` does not implement `to_partial_path`, I get the usual error: `'<Contentful::Array total=3 skip=0 limit=100>' is not an ActiveModel-compatible object. It must implement :to_partial_path.`

Let me know if there's any further details I can provide about my use case :)

**Comment by arielkirkwood** [comment]
In case anyone else needs a work around, instead of doing
```ruby
<%= render @collection %>
```
where `@collection` is a `Contentful::Array`, I'm doing
```ruby
<%= render @collection.to_a %>
```

**Comment by arielkirkwood** [comment]
@dlitvakb @pxlpnk My understanding is this wouldn't be a huge lift, would you like me to put together a PR?

**Comment by dlitvakb** [comment]
Hey @arielkirkwood,

If you can that'd be great, since I don't quite understand what the issue is.

Cheers
